directory : "services"
base_class : "BaseService"
services:
  get_user_data :
    module : "organzation_service"
    class : "OrganizarionService"
    type : ["GET", "POST"]
  create_user:
    module: "user_service"
    class: "UserService"
    type: ["GET", "POST"]

