directory : "services"
base_class : "BaseService"
services:
  signup_organization :
    module : "organization_service"
    class : "OrganizationService"
    type : ["POST"]
    session: false
  create_user :
    module : "user_service"
    class : "UserService"
    type : ["POST"]
  login :
    module: "user_service"
    class: "UserService"
    type: ["POST"]
    session: false
  add_user_organization :
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  save_user_profile :
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  get_user_info :
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_user_types:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_organization_types:
    module : "organization_service"
    class : "OrganizationService"
    type : ["GET"]
    session: false
  is_duplicate_user:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_organization_details:
    module: "organization_service"
    class: "OrganizationService"
    type: ["GET"]
  add_user_record:
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  request_user_records:
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  logout:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_all_data_request:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_all_request_status:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_user_record:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  get_block_types:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
  approve_data_request:
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  deny_data_request:
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  remove_user_from_organization:
    module: "user_service"
    class: "UserService"
    type: ["POST"]
  get_approved_request_data:
    module: "user_service"
    class: "UserService"
    type: ["GET"]
